// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj4n0G7ANQ1qH_0RPZv6IrN9DrvSSzSik',
    appId: '1:973155968571:web:ddb596bf6df70a14685e1e',
    messagingSenderId: '973155968571',
    projectId: 'gloomhaven-character-manager',
    authDomain: 'gloomhaven-character-manager.firebaseapp.com',
    storageBucket: 'gloomhaven-character-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABTcQyzJQf0Sv68xAzxfF5hJ4zyHrlJio',
    appId: '1:973155968571:android:4ed89d7876b2a97f685e1e',
    messagingSenderId: '973155968571',
    projectId: 'gloomhaven-character-manager',
    storageBucket: 'gloomhaven-character-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtVgRwP12YUVc_p0j-xQVum6Zq2DeK02s',
    appId: '1:973155968571:ios:b5175d12bdf2df08685e1e',
    messagingSenderId: '973155968571',
    projectId: 'gloomhaven-character-manager',
    storageBucket: 'gloomhaven-character-manager.appspot.com',
    iosClientId: '973155968571-u6vnp15gca1447htjqg1248sd6aq0l71.apps.googleusercontent.com',
    iosBundleId: 'com.glmhvn-chr-mngr.app',
  );
}
