// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj4n0G7ANQ1qH_0RPZv6IrN9DrvSSzSik',
    appId: '1:973155968571:web:535dcd374bc9b820685e1e',
    messagingSenderId: '973155968571',
    projectId: 'gloomhaven-character-manager',
    authDomain: 'gloomhaven-character-manager.firebaseapp.com',
    storageBucket: 'gloomhaven-character-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABTcQyzJQf0Sv68xAzxfF5hJ4zyHrlJio',
    appId: '1:973155968571:android:75df60b39971f960685e1e',
    messagingSenderId: '973155968571',
    projectId: 'gloomhaven-character-manager',
    storageBucket: 'gloomhaven-character-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtVgRwP12YUVc_p0j-xQVum6Zq2DeK02s',
    appId: '1:973155968571:ios:5609be55d2f72cc4685e1e',
    messagingSenderId: '973155968571',
    projectId: 'gloomhaven-character-manager',
    storageBucket: 'gloomhaven-character-manager.appspot.com',
    iosClientId: '973155968571-mudp3iiphc1iuusrb3gb4hp9an99hn47.apps.googleusercontent.com',
    iosBundleId: 'com.example.gloomhavenCharacterManager',
  );
}
